Lint/AssignmentInCondition:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  CountComments: false
  Max: 20

Metrics/PerceivedComplexity:
  Max: 15

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/Documentation:
  Enabled: false

Style/FileName:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise
