Lint/AssignmentInCondition:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/Documentation:
  Enabled: false

Style/FileName:
  Enabled: false

Style/LineLength:
  Max: 100

Style/MethodLength:
  CountComments: false  # count full line comments?
  Max: 20

Style/SignalException:
  EnforcedStyle: only_raise
